[package]
name = "sockets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rupnp = "1.1.0"
futures = "0.3.24"
tokio = "1.20.1"

