[package]
name = "sockets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

igd = "0.12.0"
public-ip = "0.2.2"
tokio = { version = "1.20.1", features = ["full"] }
local-ip-address = "0.4.8"
